steps:
  - label: ":windows: :electron: Package"
    command:
      - ".\\.buildkite\\windows\\build-and-upload-release"
    agents:
      - "os=windows"
      - "queue=electron-build"

  - label: ":linux: :electron: Package"
    command:
      - ".buildkite/linux/build-and-upload-release.sh"
    agents:
      - "os=linux"
      - "queue=electron-build"
