steps:
  - label: ":windows: :electron: Package ia32"
    command:
      - ".\\.buildkite\\windows\\build-and-upload-release ia32"
    agents:
      os: "windows"
      queue: "electron-build"

  - label: ":windows: :electron: Package x64"
    command:
      - ".\\.buildkite\\windows\\build-and-upload-release x64"
    agents:
      os: "windows"
      queue: "electron-build"

  - label: ":linux: :electron: Package"
    command:
      - ".buildkite/nix/build-and-upload-release.sh linux"
    agents:
      os: "linux"
      queue: "electron-build"

  - label: ":mac: :electron: Package"
    command:
      - ".buildkite/nix/build-and-upload-release.sh darwin"
    agents:
      os: "darwin"
      queue: "electron-build"
