steps:
  - label: ":windows: :electron: Package"
    command:
      - ".\\.buildkite\\windows\\build-and-upload-release"
    agents:
      - "os=windows"
      - "queue=electron-build"

  - label: ":linux: :electron: Package"
    command:
      - ".buildkite/nix/build-and-upload-release.sh linux"
    agents:
      - "os=linux"
      - "queue=electron-build"

  - label: ":mac: :electron: Package"
    command:
      - ".buildkite/nix/build-and-upload-release.sh darwin"
    agents:
      - "os=darwin"
      - "queue=electron-build"
